app:
  port: 6969

database:
  driver: sqlite3
  host:  sample.db
  port:
  dbname: 
  username: 
  password: 
  migration: false

extension:
  master_generator: true
  cors_enabled: true
  security_enabled: true

log:
  request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status} ${latency}

staticcontents:
  enabled: true

swagger:
  enabled: true
  path: /doc/.*

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /swagger/.*
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
  admin_path:
    - /api/.*

